
FROM mysql:latest

# Script SQL para crear la BBDD
COPY src/BBDD/init.sql /docker-entrypoint-initdb.d/

# Archivo CSV con el contenido de las tablas
COPY src/BBDD/canciones2.csv /var/lib/mysql-files/

# Configurar variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=sonder
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=secret