version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu:latest
      docker_layer_caching: true   

    steps:
      - checkout

      - run:
          name: Build and deploy Docker Compose
          command: |
            docker-compose up -d

workflows:
  deploy:
    jobs:
      - deploy



