version: 2.1

jobs:
  docker-tests:
    machine:
      image: ubuntu-2304:current
    steps:
      - checkout
      - run:
          name: "Running tests in Docker container"
          command: docker run -t -v `pwd`:/app/test pvalenz23/sonder

workflows:
  all-tests:
    jobs:
      - docker-tests