version: 2.1

jobs:
  docker-tests:
    docker:
      - image: pvalenz23/sonder
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            apt-get update
            apt-get install -y docker.io
      - run:
          name: "Running tests in Docker"
          command: docker run -t -v `pwd`:/app/test pvalenz23/sonder      

workflows:
  version: 2
  docker-ci-tests:
    jobs:
      - docker-tests
