version: 2.1

jobs:
  deploy:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
        name: Install Docker Compose
        environment:
          COMPOSE_VERSION: '1.29.2'
        command: |
          curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build and deploy Docker Compose
          command: |
            sudo /usr/local/bin/docker-compose up -d

workflows:
  tests:
    jobs:
      - deploy
