version: 2.1

jobs:
  deploy:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Build and deploy Docker Compose
          command: |
            docker-compose up -d


