version: 2.1

jobs:
  deploy:
    docker:
      - image: python:3.9

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build and deploy Docker Compose
          command: |
            docker-compose up -d

workflows:
  tests:
    jobs:
      - deploy



