version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current   

    steps:
      - checkout

      - run:
          name: Build and deploy Docker Compose
          command: |
            docker-compose up -d