name: Test 

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configurando Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Instalando dependencias
        run: |
          python -m pip install --upgrade pip
          pip install invoke
      
      - name: Ejecutar test
        run: |
          cd src
          invoke test
        