name: Ejecutar tes de contenedores
run-name: ${{ github.actor }} esta ejecutando test en los contenedores 🚀

on: 
  push:
    # paths:
    #   - 'src/**' 

jobs:
  docker-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_HOST: mysql
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sonder
          MYSQL_USER: myuser
          MYSQL_PASSWORD: secret
        ports:
          - "3306:3306"
    steps:
      - name: Copia del repositorio
        uses: actions/checkout@v4

      - name: Run docker test
        run: |
          docker run -t -v $(pwd):/app/test pvalenz23/sonder:latest
          docker run -t -v $(pwd):/app/test ghcr.io/valenz23/sonder:latest

        